version: '3.7'
services:
  api:
    container_name: rest-api
    build:
      context: .
      dockerfile: ./dockerfile.production
    ports:
      - 80:3000
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      PORT: 80
      DATABASE_URL: postgresql://myuser:mypassword@localhost:5432/mydatabase?schema=myschema
  postgres:
    container_name: rest-api-postgres
    image: postgres:13
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:

volumes:
  postgres:
    name: database
